# Generated by Django 4.2 on 2023-04-22 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('fecha_Publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Contenido', models.TextField()),
            ],
        ),
    ]
